/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * VibeCore API
 * OpenAPI spec version: v1
 */

export interface TodoItem {
  id?: number;
  /** @nullable */
  title?: string | null;
  isCompleted?: boolean;
  createdAt?: string;
  /** @nullable */
  completedAt?: string | null;
}
