/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * VibeCore API
 * OpenAPI spec version: v1
 */

export interface UserInfoDto {
  isAuthenticated?: boolean;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  email?: string | null;
}
