/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * VibeCore API
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  UserInfoDto
} from '.././models';

import { customFetch } from '.././client';




export const getApiUserCurrent = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<UserInfoDto>(
      {url: `/api/User/current`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiUserCurrentQueryKey = () => {
    return [
    `/api/User/current`
    ] as const;
    }

    
export const getGetApiUserCurrentQueryOptions = <TData = Awaited<ReturnType<typeof getApiUserCurrent>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserCurrent>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiUserCurrentQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUserCurrent>>> = ({ signal }) => getApiUserCurrent(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiUserCurrent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiUserCurrentQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUserCurrent>>>
export type GetApiUserCurrentQueryError = unknown


export function useGetApiUserCurrent<TData = Awaited<ReturnType<typeof getApiUserCurrent>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserCurrent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUserCurrent>>,
          TError,
          Awaited<ReturnType<typeof getApiUserCurrent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUserCurrent<TData = Awaited<ReturnType<typeof getApiUserCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserCurrent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUserCurrent>>,
          TError,
          Awaited<ReturnType<typeof getApiUserCurrent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUserCurrent<TData = Awaited<ReturnType<typeof getApiUserCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserCurrent>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiUserCurrent<TData = Awaited<ReturnType<typeof getApiUserCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserCurrent>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiUserCurrentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



